config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'sessions#home'
get '/signup' => 'users#new' 
post '/signup' => 'users#create' 

get '/login' => 'sessions#new'
post 'login' => 'sessions#create'
get '/logout' => 'sessions#destroy' 
get "/auth/google_oauth2/callback" => 'sessions#google' 

resources :users 
resources :users, only: [:show] do 
  resources :rentals, only: [:index]
end 

post '/rentals', to: 'rentals#create'
get '/rentals/:id', to: 'rentals#update'

resources :movies, only: [:index]
resources :movies, only: [:show] do 
  resources :reviews
end 



end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :rentals
    has_many :movies, through: :rentals 
    has_many :reviews 
    validates_presence_of :username 
    validates_uniqueness_of :username 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #before_action :redirect_if_not_logged_in
    #skip_before_action :redirect_if_not_logged_in, only: [:new, :create]
    #before_action :no_url_hacking, only: [:show, :edit, :update]


    def new 
        @user = User.new 
    end 

    def create 
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id
            redirect_to @user  
        else 
            render :new 
        end 
    end 

    def show 
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end 

    def edit 
        @user = User.find_by_id(params[:id])
    end 

    def update 
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path(@user)
        else 
            flash[:message] = "Please fill in all fields"
            render :edit
        end 
    end 

    def index 
        @users = User.all 
    end 

    private 

    def user_params 
        params.require(:user).permit(:username, :email, :password, :age)
    end 

    def no_url_hacking
        redirect_to '/' unless current_user.id.to_s == params[:id]
      end
end

app/helpers/users_helper.rb
module UsersHelper

    def check_for_age(user)
        statement =
        "You are old enough to see movies with a rating of "
    
        under_thirteen = "Must have Parental Guidance"
        under_seventeen = "PG, and PG13."
        over_seventeen = "PG, PG13 and R."

    
    
         if user.age
           if user.age < 13
            under_thirteen
           elsif user.age < 17
            statement + under_seventeen
           else
            statement + over_seventeen
           end
         end
       end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %> 
    <%= f.label :email %>
    <%= f.email_field :email, required: true %>: 
    <br>
    <br>
    <%= f.label :username %>
    <%= f.text_field :username, required: true %>: 
    <br>
    <br>
    <%= f.label :age %> 
    <%= f.number_field :age %> 
    <br>
    <br>
    <%= f.label :password %> 
    <%= f.password_field :password, required: true %>: 
    <br>
    <br>
    <%= f.submit "submit" %> 

<% end %> 

app/views/users/edit.html.erb
<h1> Edit Your Profile </h1>

<%= render partial: 'form', locals: {users: @users} %>

app/views/users/index.html.erb
<% @users.each do |user| %> 
    Username: <%= user.username %> 
    <br>
    Email: <%= user.email %> 
    <br>
    Age: <%= user.age %>
    <br>
    Has reviewed <%= user.reviews.size %> movie(s)
    <br> 
    <br>
    <% end %> 

app/views/users/new.html.erb
<center>
<h1> Sign Up </h1>

<%= render partial: 'form', locals: {users: @users} %>

<br>
<h4>Already have an account <hr></h4>
<%= link_to "Login here", login_path %> 
</center>

app/views/users/show.html.erb
<h1> Hello <%= @user.username %> </h1>
<p>Email: <%= @user.email %></p>
<p>Age: <%= @user.age %></p>
<br>
<br>
<div style="width:50%">
  <%= check_for_age(@user) %>
</div>
<br>
<br>


<h3><%= link_to "Edit your profile", edit_user_path(@user.id) %></h3>
 